CC=g++

all: intersection car_client car_listener

intersection: intersection.cpp
	$(CC) -std=c++11 -fopenmp -o intersection intersection.cpp

car_client: car_client.cpp
	$(CC) -std=c++11 -fopenmp -o car_client car_client.cpp

car_listener: car_listener.cpp
	$(CC) -std=c++11 -fopenmp -o car_listener car_listener.cpp
