CC=g++

all: car_client car_listener

car_client: car_client.cpp
	$(CC) -std=c++11 -fopenmp -o car_client car_client.cpp

car_listener: car_listener.cpp
	$(CC) -std=c++11 -fopenmp -o car_listener car_listener.cpp
